/**
 * simulator.js - HydroSync Industrial SCADA Physics & Safety Engine
 * 
 * Implements IEC 61508 / SIL-inspired Industrial Protection Layers:
 * 1. Cavitation & Dry-Run Interlock with Hysteresis (5% Cutoff, 15% Release)
 * 2. Water Hammer Soft Ramp (Slew-Rate Limiter <= 12%/s)
 * 3. Pump Motor Thermal Modeling & Duty Derating (Trip at 85°C)
 * 4. Hydraulic Burst & Major Leakage Detection
 * 5. Root Asphyxiation / Anti-Flooding Interlock (>88% VWC Cutoff)
 * 6. Sensor Health & Low-Pass Telemetry Filtering
 */

// --- Physical Constants & Tuning ---
const DT = 1.0; // 1-second simulation step
const AMBIENT_TEMP = 24.0; // °C
const TANK_RECHARGE_RATE = 0.4; // Baseline L/s natural replenishment
const PUMP_MAX_FLOW = 25.0; // L/min at 100% PWM
const WATER_PRICE_PER_LITER = 0.045; // $ per liter

// --- Simulation State ---
let state = {
  // Agronomic Telemetry
  vwc: 48.0, // Active Soil Moisture %
  filteredVwc: 48.0,
  setpoint: 55.0,
  soilType: 'loam',
  tankCapacityL: 200,
  tankVolumeL: 170.0,
  tankVolumePct: 85.0,
  flowRate: 0.0,
  waterSaved: 68.0,
  waterSavedL: 142.5,
  ambientTemp: 24.0,
  et0: 4.2, // Evapotranspiration mm/day

  // Actuator & Motor Physics
  pumpDuty: 0.0,        // Commanded PWM %
  effectivePwm: 0.0,    // Post-Slew-Rate PWM %
  motorTemp: 24.0,      // Motor Coil Temperature °C
  isManual: false,
  manualPwm: 0.0,

  // PID Internal Variables
  kp: 2.2,
  ki: 0.08,
  kd: 0.4,
  pTerm: 0.0,
  iTerm: 0.0,
  dTerm: 0.0,
  error: 0.0,
  lastError: 0.0,
  integralAcc: 0.0,

  // Multi-Zone Micro-Plots Heatmap
  activeZoneId: 'A1',
  zones: [
    { id: 'A1', crop: 'Wheat', moisture: 48.0, setpoint: 48.0, absorptionRate: 1.0 },
    { id: 'A2', crop: 'Tomatoes', moisture: 64.0, setpoint: 65.0, absorptionRate: 1.4 },
    { id: 'A3', crop: 'Olives', moisture: 35.0, setpoint: 35.0, absorptionRate: 0.6 },
    { id: 'B1', crop: 'Barley', moisture: 41.0, setpoint: 42.0, absorptionRate: 0.9 },
    { id: 'B2', crop: 'Corn', moisture: 59.0, setpoint: 60.0, absorptionRate: 1.3 },
    { id: 'B3', crop: 'Potatoes', moisture: 54.0, setpoint: 55.0, absorptionRate: 1.1 }
  ],

  // 🛡️ INDUSTRIAL SAFETY & INTERLOCK MATRIX
  systemHealth: 'NOMINAL', // 'NOMINAL' | 'DEGRADED' | 'EMERGENCY_LOCK'
  interlocks: {
    dryRun: false,       // Reservoir Cavitation Lock (< 5%)
    thermalTrip: false,  // Motor Coil Overheat (> 85°C)
    pipeBurst: false,    // Hydraulic Burst / Runaway Flow
    floodRisk: false,    // Soil Saturation Lock (> 88%)
    sensorFault: false   // Signal Loss / Out of Bounds
  },
  activeFaults: [],
  burstPipeCounter: 0
};

// Disturbance state
let activeDisturbance = null; // 'drought' | 'rain' | null
let disturbanceDuration = 0;

/* ==========================================================================
 *  CORE SAFETY SUB-ROUTINES
 * ========================================================================== */

/**
 * 1. Water Hammer Slew-Rate Limiter (Soft Ramp)
 * Prevents mechanical pipe fractures by limiting PWM delta to max 12% per second.
 */
function applySlewRate(targetPwm) {
  const MAX_SLEW = 12.0; // Maximum PWM % change per second
  const delta = targetPwm - state.effectivePwm;

  if (Math.abs(delta) <= MAX_SLEW) {
    state.effectivePwm = targetPwm;
  } else if (delta > 0) {
    state.effectivePwm += MAX_SLEW;
  } else {
    state.effectivePwm -= MAX_SLEW;
  }

  state.effectivePwm = Math.max(0.0, Math.min(100.0, state.effectivePwm));
  return state.effectivePwm;
}

/**
 * 2. Motor Thermal Physics Model
 * Computes Joule heating vs convective cooling. Trips at 85°C.
 */
function updateMotorThermalModel() {
  const dutyFraction = state.effectivePwm / 100.0;
  
  // Joule heating generated by electrical duty
  const heatGen = (dutyFraction * dutyFraction) * 2.2; 
  // Convective air cooling towards ambient
  const heatDissipation = 0.08 * (state.motorTemp - AMBIENT_TEMP);

  state.motorTemp += (heatGen - heatDissipation) * DT;
  state.motorTemp = Math.max(AMBIENT_TEMP, state.motorTemp);

  // Overheat trip logic with hysteresis (Trips at 85°C, resets below 60°C)
  if (state.motorTemp >= 85.0 && !state.interlocks.thermalTrip) {
    state.interlocks.thermalTrip = true;
  } else if (state.motorTemp <= 60.0 && state.interlocks.thermalTrip) {
    state.interlocks.thermalTrip = false;
  }
}

/**
 * 3. Reservoir Cavitation & Dry-Run Protection (Hysteresis)
 */
function updateReservoirCavitation() {
  state.tankVolumePct = (state.tankVolumeL / state.tankCapacityL) * 100.0;

  // Trip cutoff at 5%
  if (state.tankVolumePct <= 5.0 && !state.interlocks.dryRun) {
    state.interlocks.dryRun = true;
  } 
  // Requires 15% replenishment to clear interlock
  else if (state.tankVolumePct >= 15.0 && state.interlocks.dryRun) {
    state.interlocks.dryRun = false;
  }
}

/**
 * 4. Hydraulic Burst & Major Leakage Detection
 * Detects if high pumping produces zero moisture accumulation.
 */
function checkHydraulicIntegrity(deltaVwc) {
  if (state.effectivePwm > 70.0 && state.flowRate > 12.0 && deltaVwc <= 0.05) {
    state.burstPipeCounter++;
    if (state.burstPipeCounter >= 12) { // 12 consecutive seconds of runaway flow
      state.interlocks.pipeBurst = true;
    }
  } else {
    state.burstPipeCounter = Math.max(0, state.burstPipeCounter - 1);
  }
}

/**
 * 5. Anti-Flooding & Root Asphyxiation Interlock
 */
function checkAntiFlooding() {
  if (state.vwc >= 88.0) {
    state.interlocks.floodRisk = true;
  } else if (state.vwc <= 80.0) {
    state.interlocks.floodRisk = false;
  }
}

/* ==========================================================================
 *  MAIN PID & PHYSICAL SIMULATION STEP
 * ========================================================================== */
function pidLoop() {
  // Update Reservoir Levels
  const waterConsumedL = (state.flowRate / 60.0) * DT;
  state.tankVolumeL = Math.max(0, state.tankVolumeL - waterConsumedL + (TANK_RECHARGE_RATE * DT));
  state.tankVolumeL = Math.min(state.tankCapacityL, state.tankVolumeL);
  updateReservoirCavitation();

  // Run Motor Thermal Dynamics
  updateMotorThermalModel();

  // Check Root Saturation
  checkAntiFlooding();

  // Determine Target Command (Manual or Closed-Loop PID)
  let rawPwmCommand = 0.0;

  if (state.isManual) {
    rawPwmCommand = state.manualPwm;
  } else {
    // Closed-loop PID Calculation
    state.error = state.setpoint - state.vwc;
    
    // Anti-windup clamping on integral accumulator
    state.integralAcc += state.error * DT;
    state.integralAcc = Math.max(-25.0, Math.min(25.0, state.integralAcc));

    const derivative = (state.error - state.lastError) / DT;
    state.lastError = state.error;

    state.pTerm = state.kp * state.error;
    state.iTerm = state.ki * state.integralAcc;
    state.dTerm = state.kd * derivative;

    let computed = state.pTerm + state.iTerm + state.dTerm;
    rawPwmCommand = Math.max(0.0, Math.min(100.0, computed));
  }

  // --- 🛡️ APPLY INDUSTRIAL INTERLOCK ENFORCEMENT ---
  state.activeFaults = [];

  if (state.interlocks.dryRun) {
    rawPwmCommand = 0.0;
    state.activeFaults.push('LOCK: RESERVOIR CAVITATION PREVENTED (LEVEL < 5%)');
  }
  if (state.interlocks.pipeBurst) {
    rawPwmCommand = 0.0;
    state.activeFaults.push('LOCK: MAJOR HYDRAULIC PIPE RUPTURE DETECTED');
  }
  if (state.interlocks.floodRisk) {
    rawPwmCommand = 0.0;
    state.activeFaults.push('LOCK: ANTI-FLOODING / ROOT ASPHYXIATION OVERRIDE');
  }
  if (state.interlocks.thermalTrip) {
    // Thermal derating: clamp to max 30% duty to allow motor cooling
    rawPwmCommand = Math.min(rawPwmCommand, 30.0);
    state.activeFaults.push('THROTTLE: MOTOR COIL THERMAL DERATING ACTIVE (TEMP > 85°C)');
  }

  // Determine Overall System Health
  if (state.interlocks.dryRun || state.interlocks.pipeBurst || state.interlocks.floodRisk) {
    state.systemHealth = 'EMERGENCY_LOCK';
  } else if (state.interlocks.thermalTrip) {
    state.systemHealth = 'DEGRADED';
  } else {
    state.systemHealth = 'NOMINAL';
  }

  // Apply Slew-Rate Limiter (Soft Ramp)
  state.pumpDuty = rawPwmCommand;
  const safePwm = applySlewRate(rawPwmCommand);

  // Compute Hydraulic Flow Rate
  state.flowRate = (safePwm / 100.0) * PUMP_MAX_FLOW;

  // Active Zone Soil Physics & Moisture Dynamics
  let soilDrainRate = 0.35; // Loam base drainage
  if (state.soilType === 'sandy') soilDrainRate = 0.65;
  if (state.soilType === 'clay') soilDrainRate = 0.18;

  // Environmental Disturbances
  let disturbanceEffect = 0.0;
  if (activeDisturbance === 'drought') {
    disturbanceEffect = -1.6;
    state.ambientTemp = 36.5;
    state.et0 = 7.8;
  } else if (activeDisturbance === 'rain') {
    disturbanceEffect = 2.4;
    state.ambientTemp = 18.0;
    state.et0 = 1.2;
    state.tankVolumeL = Math.min(state.tankCapacityL, state.tankVolumeL + 2.5);
  } else {
    state.ambientTemp = AMBIENT_TEMP;
    state.et0 = 4.2;
  }

  if (disturbanceDuration > 0) {
    disturbanceDuration--;
    if (disturbanceDuration === 0) activeDisturbance = null;
  }

  // Moisture Delta calculation
  const irrigationInflow = (state.flowRate * 0.08);
  const deltaVwc = (irrigationInflow - soilDrainRate + disturbanceEffect) * DT;

  // Integrity Check for Bursts
  checkHydraulicIntegrity(deltaVwc);

  // Update active zone soil moisture
  state.vwc = Math.max(5.0, Math.min(99.0, state.vwc + deltaVwc));

  // Low-Pass Sensor Filter
  state.filteredVwc = (0.85 * state.filteredVwc) + (0.15 * state.vwc);

  // Update Zones Array
  state.zones.forEach(z => {
    if (z.id === state.activeZoneId) {
      z.moisture = state.vwc;
    } else {
      // Natural passive decay for idle zones
      z.moisture = Math.max(10.0, z.moisture - 0.08);
    }
  });

  // Financial ROI & Water Conservation Calculation
  const baselineConsumption = 18.0; // Average traditional flood irrigation L/min
  const savedThisSec = Math.max(0, (baselineConsumption - state.flowRate) / 60.0);
  state.waterSavedL += savedThisSec;
  state.waterSaved = Math.max(10, Math.min(92, ((baselineConsumption - state.flowRate) / baselineConsumption) * 100));
}

/* ==========================================================================
 *  PUBLIC API & EVENT HANDLERS
 * ========================================================================== */

function getState() {
  return {
    ...state,
    vwc: Number(state.vwc.toFixed(1)),
    filteredVwc: Number(state.filteredVwc.toFixed(1)),
    pumpDuty: Number(state.effectivePwm.toFixed(1)),
    rawCommandDuty: Number(state.pumpDuty.toFixed(1)),
    flowRate: Number(state.flowRate.toFixed(1)),
    motorTemp: Number(state.motorTemp.toFixed(1)),
    tankVolumeL: Number(state.tankVolumeL.toFixed(1)),
    tankVolumePct: Number(state.tankVolumePct.toFixed(1)),
    waterSaved: Number(state.waterSaved.toFixed(1)),
    waterSavedL: Number(state.waterSavedL.toFixed(1)),
    financialSavingsUsd: Number((state.waterSavedL * WATER_PRICE_PER_LITER).toFixed(3)),
    error: Number(state.error.toFixed(2))
  };
}

function setPIDParams(params) {
  if (params.kp !== undefined) state.kp = Math.max(0, Number(params.kp));
  if (params.ki !== undefined) state.ki = Math.max(0, Number(params.ki));
  if (params.kd !== undefined) state.kd = Math.max(0, Number(params.kd));
}

function setTargetSetpoint(sp) {
  state.setpoint = Math.max(0.0, Math.min(100.0, Number(sp)));
  const currentZone = state.zones.find(z => z.id === state.activeZoneId);
  if (currentZone) currentZone.setpoint = state.setpoint;
}

function setSettings(settings) {
  if (settings.setpoint !== undefined) setTargetSetpoint(settings.setpoint);
  if (settings.tankCapacity !== undefined) state.tankCapacityL = Math.max(20, Number(settings.tankCapacity));
  if (settings.soilType !== undefined) state.soilType = String(settings.soilType);
}

function injectDisturbance(type) {
  activeDisturbance = type;
  disturbanceDuration = 25; // 25 seconds of severe weather
  if (type === 'rain') {
    // Rain clears burst/leak flags
    state.interlocks.pipeBurst = false;
    state.burstPipeCounter = 0;
  }
}

function setActiveZone(zoneId) {
  state.activeZoneId = zoneId;
  const target = state.zones.find(z => z.id === zoneId);
  if (target) {
    state.vwc = target.moisture;
    state.filteredVwc = target.moisture;
    state.setpoint = target.setpoint;
    state.integralAcc = 0; // Reset windup on zone switch
  }
}

function setManualMode(enabled, pwm) {
  state.isManual = Boolean(enabled);
  state.manualPwm = Math.max(0.0, Math.min(100.0, Number(pwm || 0)));
}

module.exports = {
  getState,
  pidLoop,
  setPIDParams,
  setTargetSetpoint,
  setSettings,
  injectDisturbance,
  setActiveZone,
  setManualMode
};